//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acikveriportal.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSetFileDetail
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public int DataSetId { get; set; }
        public string FileDataId { get; set; }
    
        public virtual DataSets DataSets { get; set; }
    }
}
